REPO_TAGLINE: Artificial intelligence • reasoning • learning
ASSETS_DIR: .github/readme
CTA_TEXT: Access the full course website
THEME: coding
SITE_URL: https://academic-codex.github.io/SCE0614-Inteligencia-Artificial

BG_1: "#020617"
BG_2: "#020617"
TEXT_MAIN: "#E5E7EB"
TEXT_MUTED: "#9CA3AF"
ACCENT: "#22D3EE"
CARD_RADIUS: "18"